name: leetcode-CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Installation depends
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          mkdir logdir
          xmake require -y
          xmake

      - name: Run TestCases and Generate Report
        run: |
          xmake run leetcode >> ./logdir/testcase_report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: TestcaseReport-macOS
          path: ./logdir
  build_on_ubuntu:
    if: 0 == 1
    runs-on: ubuntu-latest
    steps:
      - name: Installation depends
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          mkdir logdir
          xmake require -y
          xmake

      - name: Run TestCases and Generate Report
        run: |
          xmake run leetcode >> ./logdir/testcase_report.txt

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: TestcaseReport-Ubuntu
          path: ./logdir
